### ISSUE TITLE
Error S is not supported

### ISSUE THREAD

**Issue by stupid-kid-af** [nitanmarcel/OEM-GSI-Builder#3]

**Comment by stupid-kid-af** [comment]
On running the workflow it shows an error "S is not supported"

**Comment by nitanmarcel** [comment]
S has been renamed to 12 in the following commit: https://github.com/erfanoabdi/ErfanGSIs/commit/c7bc816b5c8496c182469f9a86203ca26a74ace1

Probably you need an updated firmware link
